# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Fix for AAPT2 "Invalid data/access denied" issues on Windows/OneDrive
kapt.incremental.apt=false
android.enableResourceOptimizations=false
android.defaults.buildfeatures.buildconfig=true
org.gradle.vfs.watch=false
